# Generated by Django 2.1.5 on 2019-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0012_companylogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyLogin',
        ),
    ]
