# Generated by Django 2.1.5 on 2019-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0013_delete_companylogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
