# Generated by Django 2.1.5 on 2019-03-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0018_auto_20190314_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
    ]
