# Generated by Django 2.1.5 on 2019-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0019_auto_20190316_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='test_id',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='company_name',
            field=models.CharField(default='NULL', max_length=125),
        ),
    ]
