# Generated by Django 2.1.5 on 2019-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_diagnose', '0021_remove_orderinfo_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
